<?php echo $this->tag->form("index/edit/".$userid); 
// print_r($userid);

?>


<h2>Edit Details</h2>
    <p>
        <label for="email">Name:</label>
        <?php echo $this->tag->textField('username'); ?> 
        <label for="password">Email:</label>
        <?php echo $this->tag->textField('email'); ?>
        <label for="password">Password:</label>
        <?php echo $this->tag->passwordField('password'); ?>
    </p>
    <p>
       
    </p>

    <p>
        <?php echo $this->tag->submitButton("submit"); ?>
    </p>

</form>