<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.tailwindcss.com" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    
</head>

<body class="h-screen overflow-hidden flex items-center justify-center" style="background: #edf2f7;">      
<h1 style="text-align:center">Login Page</h1>
             <?php echo $this->tag->form(['class'=>'w-full sm:w-[250px] p-4 mx-auto flex flex-col bg-gray-200 rounded-md',"login/register"]);  ?>
             
             <?php echo $this->tag->textField(['placeholder'=>'Enter Email','class'=>'px-3 py-2.5 mb-3 border-2 border-gray-800 rounded-md',"email"]); ?>
             <?php echo $this->tag->passwordField(['placeholder'=>'Enter Passwords','class'=>'px-3 py-2.5 mb-3 border-2 border-gray-800 rounded-md',"password"]); ?> 
                 <?php echo $this->tag->submitButton(['class'=>'px-2 py-1.5 rounded-md bg-blue-600 hover:bg-blue-700 ttext-white mt-3',"Login"]);?>
           <div class="checkbox mb-3"><label>
          <input  type="checkbox" value="remember-me" > Remember me
        </label></div>
        <p>Don’t have Account?<a href='signup' class='text-primary'> Signup</a></p>
              </form>
             
         
   
    
</body>
</html>