<table>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Full Blog</th>
    </tr>
    <?php foreach ($page->getItems() as $item) { ?>
    <tr>
        <td><?php echo $item['blogid']; ?></td>
        <td><?php echo ($item['blogname']); ?></td>
        <td><?php echo $item['fullblog']; ?></td>
    </tr>
    <?php } ?>
</table>
<a href="/invoices/list">First</a>
<a href="/invoices/list?page=<?= $page->getPrevious(); ?>">Previous</a>
<a href="/invoices/list?page=<?= $page->getNext(); ?>">Next</a>
<a href="/invoices/list?page=<?= $page->getLast(); ?>">Last</a>

<?php echo "Page {$page->getCurrent()}  of {$page->getLast()}"; ?>