<?php

echo "<h2 style='text-align:center'>Server Date & Time-</h2>";
echo "<h2 style='text-align:center'class='text-danger'>".$time."</h2>";

echo "<h1 style='text-align:center'>Basics</h1>";


echo PHP_EOL;

echo $this->tag->linkTo([
    'signup',
    'Sign Up Here!', 'class' => 'btn btn-dark' ]);
echo $this->tag->linkTo([
    'login',
    'Login Here!', 'class' => 'btn btn-primary' ]);
    

echo $this->tag->linkTo([
    'dashboard',
    'All Details', 'class' => 'btn btn-dark' ]);
    echo $this->tag->linkTo([
        'index/logout',
        'Logout', 'class' => 'btn btn-danger' ]);
if ($this->cookies->has('remember-me')) { 
    //  print_r($this->cookies->get('remember-me')->getValue());
   
    if ($users->count() != 0  ) {
       
       ?>
      
        
      
        <table class="table table-bordered table-hover" >
            <thead class="thead-light">
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Email</th>
                <th>Password</th>
                <th>Action</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <td colspan="3">Users quantity: <?php echo $users->count(); ?></td>
            </tr>
            </tfoot>
            <tbody>
            <?php foreach ($users as $user) { ?>
                <tr>
                    <td><?php echo $user->id; ?></td>
                    <td><?php echo $user->name; ?></td>
                    <td><?php echo $user->email; ?></td>
                    <td><?php echo $user->password; ?></td>
                    <td><?php echo $this->tag->linkTo([
                            'edit/edit/'.$user->id,
                            'Edit', 'class' => 'btn btn-primary' ]);?>
                    <?php echo $this->tag->linkTo([
                            'index/delete/'.$user->id,
                            'Delete', 'class' => 'btn btn-danger' ]);?></td>

                </tr>
            <?php
}         ?>
            </tbody>
        </table>
        <?php
    }
}