<?php

?>

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.88.1">
  <title>Dashboard Template · Bootstrap v5.1</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/dashboard/">



  <!-- Bootstrap core CSS -->
  <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link href="../node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">


  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>


  <!-- Custom styles for this template -->
  <link href="../../public/assets/css//style.css" rel="stylesheet">
</head>

<body>

  <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="home.php">Home</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" 
    data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" 
    aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <!-- <div class="nav-item text-nowrap">
        <a href='signIn'><button value="yes" name="sigin" class="nav-link px-3 text-white bg-dark">Log In</button></a>
      </div>
    </div>
    <div class="navbar-nav">
      <div class="nav-item text-nowrap">
        <a href='adduser'><button value="yes" name="signup" class="nav-link px-3 text-white bg-dark">Signup</button></a>
      </div>
    </div> -->
    
    <div class="navbar-nav">
      <div class="nav-item text-nowrap">
        <a href='/dashboard/logout'><button value="yes" name="logout" class="nav-link px-3 text-white bg-dark">Logout</button></a>
       
      </div>
    </div>
    </div>
  </header>
<div class="container-fluid">
      <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
          <div class="position-sticky pt-3">
            <ul class="nav flex-column">
                <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="index">
                  <span data-feather=""></span>
                Home
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="products">
                  <span data-feather="users"></span>
                  Add Products
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="shop">
                  <span data-feather="users"></span>
                  Shop
                </a>
              </li>
             
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="layers"></span>
                 
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2"></h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group me-2">
                <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
                <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
              </div>
              <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <span data-feather="calendar"></span>
                This week
              </button>
            </div>
          </div>
          <div> 
            <h2>Admin Profile</h2>
            <table class="table table-bordered table-hover">
            <thead class="thead-light">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Password</th>
                <th>Action</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <td colspan="3"><?php ?></td>
            </tr>
            </tfoot>
            <tbody>
              <?php ?>
              <?php  ?>
              
            <?php foreach ($users as $user) { ?>
              <?php if($user->role=="admin") {?>
                <tr>
                    <td><?php echo $user->id; ?></td>
                    <td><?php echo $user->name; ?></td>
                    <td><?php echo $user->email; ?></td>
                    <td><?php echo $user->password; ?></td>
                    <td><?php echo $this->tag->linkTo([
                            'edit/edit/'.$user->id,
                            'Edit', 'class' => 'btn btn-primary' ]);?>
                    <?php echo $this->tag->linkTo([
                            'index/delete/'.$user->id,
                            'Delete', 'class' => 'btn btn-dark' ]);?></td>

                </tr>
            <?php
}
}     ?>
            </tbody>
        </table>

        </div>
        <div> 
            <h2>Users's Profile</h2>
            <table class="table table-bordered table-hover">
            <thead class="thead-light">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Password</th>
                <th>Action</th>
                <th>Operation</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <td colspan="3"><?php ?></td>
            </tr>
            </tfoot>
            <tbody>
            <?php foreach ($users as $user) {
                ?>
                <?php if ($user->role=="user") {
                ?>
                <?php $act="approve";
                  $act1='app';
                // if ($user->status=='approve') {
                //      $act1='dis';
                //      $act='dissapprove';
                // }
         ?>
                <tr>
                    <td><?php echo $user->id; ?></td>
                    <td><?php echo $user->name; ?></td>
                    <td><?php echo $user->email; ?></td>
                    <td><?php echo $user->password; ?></td>
                    <td><?php //echo  "<form action='/approve/approve'method='POST'><button name='authenticate' value='".$act1."-".$user->id."'>".$act."</button></form>" ?></td>
                    <td><?php echo $this->tag->linkTo([
                            'edit/edit/'.$user->id,
                            'Edit', 'class' => 'btn btn-primary' ]);?>
                            <?php echo $this->tag->linkTo([
                            'index/delete/'.$user->id,
                            'Delete', 'class' => 'btn btn-dark'  ]);?></td>

                </tr>
            <?php
}
}     ?>
            </tbody>
        </table>

        </div>
          
            
            

        </div>
        <div>
        </div>
      <!-- <form action='' method='post'>
        
    </form> -->

      

        </main>
      </div>
      
    </div>
    
  <script src="../node_modules/bootstrap/dist/js/bootstrap.bundle.js" 
  integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>

</html>